import { leads } from "@/lib/db/leads";
import { SUBSCRIBER_TOPIC, isSubscriber } from "@/lib/risefinder";

/**
 * /admin/risefinder — who has asked for the daily briefing.
 *
 * WHY THIS IS NOT PART OF /admin/leads. A lead is somebody who asked about
 * expert calls and is worth a reply; a subscriber gave an email address to
 * receive a briefing and is worth an email. They need different actions, and
 * mixing them breaks the one number the leads page exists to produce: cost per
 * lead. Subscribers arrive free and in volume, so counting them as leads would
 * make paid search look cheaper every time somebody signed up here — a metric
 * quietly improving for a reason that has nothing to do with the ads.
 *
 * So the leads page filters these out and this page is the only place they
 * appear. One storage table, two audiences, kept apart at the read.
 */

export const metadata = { title: "RiseFinder subscribers — FieldSignal" };

/** Always read fresh — a signup a minute ago must show up. */
export const dynamic = "force-dynamic";

function fmt(iso: string) {
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default async function AdminRiseFinderPage() {
  let all;
  try {
    all = await leads.list();
  } catch (err) {
    return (
      <div className="px-4 sm:px-9 py-12 max-w-3xl">
        <h1 className="font-sans font-medium text-section leading-[1] tracking-[-0.022em] text-ink">
          RiseFinder subscribers
        </h1>
        <div className="bg-paper-2 border-l-4 border-red px-5 py-4 mt-6">
          <p className="text-body text-ink font-medium">
            The leads table doesn&apos;t exist yet.
          </p>
        </div>
        <p className="text-body text-ink-2 mt-4">
          Open the Supabase SQL editor, paste the contents of{" "}
          <code className="font-mono text-mono">supabase/leads.sql</code>, and
          run it once. Subscribers are stored in the same table with topic{" "}
          <code className="font-mono text-mono">{SUBSCRIBER_TOPIC}</code>.
        </p>
        <p className="font-mono text-micro text-ink-3 mt-6 break-words">
          {err instanceof Error ? err.message : String(err)}
        </p>
      </div>
    );
  }

  const subs = all.filter(isSubscriber);
  const today = new Date().toISOString().slice(0, 10);
  const todayCount = subs.filter((s) =>
    s.submittedAt.startsWith(today),
  ).length;
  const week = Date.now() - 7 * 864e5;
  const weekCount = subs.filter(
    (s) => new Date(s.submittedAt).getTime() >= week,
  ).length;

  return (
    <div className="px-4 sm:px-9 py-12">
      <h1 className="font-sans font-medium text-section leading-[1] tracking-[-0.022em] text-ink">
        RiseFinder subscribers
      </h1>
      <p className="text-body text-ink-2 mt-4 max-w-2xl">
        Addresses left on{" "}
        <a
          href="/risefinder"
          className="text-ink underline decoration-rule-2 underline-offset-4 hover:text-red"
        >
          /risefinder
        </a>
        . Nothing is sent automatically — the digest is generated by{" "}
        <code className="font-mono text-mono">scripts/build_digest.py</code> in
        the RiseFinder project and sent deliberately.
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-px bg-rule mt-8 mb-10">
        {[
          { label: "Total subscribers", value: subs.length },
          { label: "Last 7 days", value: weekCount },
          { label: "Today", value: todayCount },
        ].map((s) => (
          <div key={s.label} className="bg-paper-2 px-7 py-6">
            <div className="font-mono text-micro uppercase tracking-[0.12em] text-ink-3 mb-2">
              {s.label}
            </div>
            <div className="font-sans text-[32px] leading-none text-ink">
              {s.value}
            </div>
          </div>
        ))}
      </div>

      {subs.length === 0 ? (
        <div className="bg-paper-2 border-l-4 border-rule-2 px-5 py-4 max-w-2xl">
          <p className="text-body text-ink">Nobody has subscribed yet.</p>
          <p className="text-body text-ink-2 mt-2">
            The form is live at /risefinder. Signups will appear here as they
            arrive.
          </p>
        </div>
      ) : (
        <div className="border border-rule overflow-x-auto">
          <table className="w-full border-collapse min-w-[520px]">
            <thead>
              <tr className="bg-paper-2 border-b border-rule-2">
                <th className="text-left px-5 py-3 font-mono text-micro uppercase tracking-[0.12em] text-ink-3">
                  Email
                </th>
                <th className="text-left px-5 py-3 font-mono text-micro uppercase tracking-[0.12em] text-ink-3">
                  Subscribed
                </th>
              </tr>
            </thead>
            <tbody>
              {subs.map((s) => (
                <tr key={s.id} className="border-b border-rule">
                  <td className="px-5 py-3 font-mono text-mono text-ink break-all">
                    <a
                      href={`mailto:${s.email}`}
                      className="hover:text-red transition-colors"
                    >
                      {s.email}
                    </a>
                  </td>
                  <td className="px-5 py-3 font-mono text-mono text-ink-2 whitespace-nowrap">
                    {fmt(s.submittedAt)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {subs.length > 0 && (
        <div className="mt-8 max-w-2xl">
          <div className="font-mono text-micro uppercase tracking-[0.12em] text-ink-3 mb-2">
            All addresses, comma separated
          </div>
          <textarea
            readOnly
            rows={3}
            value={subs.map((s) => s.email).join(", ")}
            className="w-full bg-paper-3 border border-ink px-4 py-3 font-mono text-mono text-ink"
          />
        </div>
      )}
    </div>
  );
}
