/**
 * Real content-modification dates for the data-driven routes, taken from the
 * git last-commit date of each content file. Generated by
 * scripts/gen-content-modified.mjs — regenerate after editing content data.
 *
 * Used for sitemap <lastmod>. A real per-section signal beats a uniform deploy
 * timestamp (which teaches crawlers to distrust the field) and beats omitting
 * it entirely. Dates reflect the last committed change to each section's data.
 */
export const CONTENT_MODIFIED: Record<string, string> = {
  services: "2026-07-24",
  industries: "2026-07-24",
  subniches: "2026-07-24",
  clients: "2026-07-24",
  caseStudies: "2026-07-25",
  complianceSubs: "2026-07-24",
  alternatives: "2026-07-24",
  compares: "2026-07-24",
  useCases: "2026-07-24",
  expertPages: "2026-07-24",
  guides: "2026-07-24",
  glossary: "2026-07-24",
  platform: "2026-07-24",
  regions: "2026-07-24",
};
